--- 
javascripts:
    
- application:
    - mootools-core-1.3-full-compat
    - mootools-more-1.3-full-compat    
    - rails
    - global
    - modal
    - overlay
    - ejs
    - view

- client:
    - mootools-core-1.3-full-compat
    - mootools-more-1.3-full-compat    
    - rails
    - global
    - modal
    - overlay
    - client
    - ejs
    - view
  	
stylesheets:

- screen:
  - screen
- print:
  - print
- ie_less_8:
  - ie

- application:
  - global
  - application

- client:
  - global
  - application
  - client
  - badge
